#define IDC_335_231	231	// Appearance: "Virtual Tile" (Button)
#define IDC_336_301	301	// System: "" (ListBox)
#define IDC_335_232	232	// Appearance: "Tile" (Button)
#define IDC_334_601	601	// General: "Enable Autohide" (Button)
#define IDC_335_233	233	// Appearance: "Stretch" (Button)
#define IDC_334_602	602	// General: "" (Edit)
#define IDC_335_211	211	// Appearance: "Thin Border" (Button)
#define IDC_335_212	212	// Appearance: "Thick Border" (Button)
#define IDC_335_213	213	// Appearance: "No Border" (Button)
#define IDC_334_100	100	// General: "Desktop Size" (Button)
#define IDC_336_100	100	// System: "Ignore Classes" (Button)
#define IDC_335_101	101	// Appearance: "Icons" (Button)
#define IDC_334_101	101	// General: "Autohide" (Button)
#define IDC_334_102	102	// General: "Desktop Change" (Button)
#define IDC_334_701	701	// General: "Use Mouse" (Button)
#define IDC_335_241	241	// Appearance: "Browse..." (Button)
#define IDC_334_702	702	// General: "Use Keyboard" (Button)
#define IDC_336_311	311	// System: "Use Double Buffer" (Button)
#define IDC_334_703	703	// General: "" (Edit)
#define IDC_335_221	221	// Appearance: "Light Background" (Button)
#define IDC_335_106	106	// Appearance: "Wallpaper" (Button)
#define IDC_335_201	201	// Appearance: "Don't Draw Icons" (Button)
#define IDC_334_501	501	// General: "" (Edit)
#define IDC_335_202	202	// Appearance: "Stretch Icons" (Button)
#define IDC_335_110	110	// Appearance: "Desktop" (Button)
#define IDC_334_502	502	// General: "" (Edit)
#define IDC_335_203	203	// Appearance: "Fixed Size Icons" (Button)
#define IDC_335_251	251	// Appearance: "" (ComboBox)

/*
const DWORD aHelpIDs[]=
{
	IDC_BACK_VIRT,	IDC_BACK_VIRT,	// Appearance: "Virtual Tile" (Button)
	IDC_IGNORE_CLASSES,	IDC_IGNORE_CLASSES,	// System: "" (ListBox)
	IDC_BACK_TILE,	IDC_BACK_TILE,	// Appearance: "Tile" (Button)
	IDC_ENABLE_AUTOHIDE,	IDC_ENABLE_AUTOHIDE,	// General: "Enable Autohide" (Button)
	IDC_BACK_STRETCH,	IDC_BACK_STRETCH,	// Appearance: "Stretch" (Button)
	IDC_AUTOHIDE_DELAY,	IDC_AUTOHIDE_DELAY,	// General: "" (Edit)
	IDC_BORDER_THIN,	IDC_BORDER_THIN,	// Appearance: "Thin Border" (Button)
	IDC_BORDER_THICK,	IDC_BORDER_THICK,	// Appearance: "Thick Border" (Button)
	IDC_BORDER_NO,	IDC_BORDER_NO,	// Appearance: "No Border" (Button)
	100,	100,	// General: "Desktop Size" (Button)
	100,	100,	// System: "Ignore Classes" (Button)
	101,	101,	// Appearance: "Icons" (Button)
	101,	101,	// General: "Autohide" (Button)
	102,	102,	// General: "Desktop Change" (Button)
	IDC_ENABLE_MOUSE,	IDC_ENABLE_MOUSE,	// General: "Use Mouse" (Button)
	IDC_BROWSE,	IDC_BROWSE,	// Appearance: "Browse..." (Button)
	IDC_ENABLE_KEYBOARD,	IDC_ENABLE_KEYBOARD,	// General: "Use Keyboard" (Button)
	IDC_DOUBLE_BUFFER,	IDC_DOUBLE_BUFFER,	// System: "Use Double Buffer" (Button)
	IDC_MOUSE_DELAY,	IDC_MOUSE_DELAY,	// General: "" (Edit)
	IDC_LIGHT_BACK,	IDC_LIGHT_BACK,	// Appearance: "Light Background" (Button)
	106,	106,	// Appearance: "Wallpaper" (Button)
	IDC_ICONS_DONTDRAW,	IDC_ICONS_DONTDRAW,	// Appearance: "Don't Draw Icons" (Button)
	IDC_SIZE_X,	IDC_SIZE_X,	// General: "" (Edit)
	IDC_ICONS_STRETCH,	IDC_ICONS_STRETCH,	// Appearance: "Stretch Icons" (Button)
	110,	110,	// Appearance: "Desktop" (Button)
	IDC_SIZE_Y,	IDC_SIZE_Y,	// General: "" (Edit)
	IDC_ICONS_FIXED,	IDC_ICONS_FIXED,	// Appearance: "Fixed Size Icons" (Button)
	IDC_BACK_LIST,	IDC_BACK_LIST,	// Appearance: "" (ComboBox)
	0, 0
};
*/

